trigger: none
pool:
  name: Ansys
steps:
- script: |
   echo "Current working directory is %CD%"
   python -m pip install -r requirements.txt
   echo "Python dependencies are installed"
  displayName: 'Install Python Dependencies'

- script: |
   echo Start packaging Python
   cd electron_ui
   pyinstaller.exe ..\downloader_backend.py --distpath python_build --workpath %TEMP% --exclude-module tkinter --onefile --noconsole  --hidden-import plyer.platforms.win.notification
   Xcopy /E /I ..\notifications python_build\notifications
  displayName: 'Build Python Exe'

- script: |
   python unittests/test_version.py
  displayName: 'Validate that all versions are updated'

- script: |
   cd electron_ui
   echo "Current working directory is %CD%"
   npm install
   echo "Dependencies are installed"
  displayName: 'Install NodeJS Dependencies'

- script: |
   cd electron_ui
   npm run dist
  displayName: 'Build Electron'

- script: |
    python "server\\upload_build_to_server.py" --channel="stable" --platform="windows_64"  --base-url="http://ottbld02:1337" --username="admin" --password="$(password)" --path="%CD%\\electron_ui\\dist"
  displayName: 'Upload build to server'